
name: Build PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc texlive-xetex fonts-noto-cjk

      - name: Convert Markdown to PDF
        run: |
          pandoc AWUS036AXML_Wireshark.md           -o output.pdf           --template=ft_template.tex           --pdf-engine=xelatex

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: pdf-output
          path: output.pdf
